<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="length" value="0.3"/>
    <xacro:property name="width" value="0.3"/>
    <xacro:property name="height" value="0.1"/>
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="caster_wheel_radius" value="0.05"/>

    <link name = "base_footprint"/>

    <link name = "base_link">
        <visual>
            <geometry>
                <box size = "${length} ${width} ${height}"/>
            </geometry>
            <material name = "white"/>
            <origin xyz = "0 0 ${wheel_radius}" rpy = "0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <box size = "${length} ${width} ${height}"/>
            </geometry>
            <origin xyz = "0 0 ${wheel_radius}" rpy = "0 0 0"/>
        </collision>
        <xacro:box_inertia m = "0.5" x = "${length}" y = "${width}" z = "${height}"
                             o_xyz = "0 0 ${wheel_radius}" o_rpy = "0 0 0"/>
    </link>

    <link name ="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius = "${wheel_radius}" length = "${wheel_width}"/>
            </geometry>
            <material name = "white"/>
            <origin xyz = "0 0 0" rpy = "${pi/2} 0 0"/>
        </visual>
        <collision>
            <geometry>    
                <cylinder radius = "${wheel_radius}" length = "${wheel_width}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "${pi/2} 0 0"/>
        </collision>
        <xacro:cylinder_inertia m = "0.05" r = "${wheel_radius}" h = "${wheel_width}"
                             o_xyz = "0 0 0" o_rpy = "${pi/2} 0 0"/>
    </link>

    <gazebo reference="left_wheel_link">
        <material>Gazebo/White</material>
    </gazebo>


    <link name ="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius = "${wheel_radius}" length = "${wheel_width}"/>
            </geometry>
            <material name = "white"/>
            <origin xyz = "0 0 0" rpy = "${pi/2} 0 0"/>
        </visual>
        <collision>
            <geometry>    
                <cylinder radius = "${wheel_radius}" length = "${wheel_width}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "${pi/2} 0 0"/>
        </collision>
        <xacro:cylinder_inertia m = "0.05" r = "${wheel_radius}" h = "${wheel_width}"
                             o_xyz = "0 0 0" o_rpy = "${pi/2} 0 0"/>
    </link>


    <gazebo reference="right_wheel_link">
        <material>Gazebo/White</material>
    </gazebo>



    <link name ="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius = "${caster_wheel_radius}"/>
            </geometry>
            <material name = "blue"/>
            <origin xyz = "0 0 ${-wheel_radius + caster_wheel_radius}" rpy = "0 0 0"/>
        </visual>
        <collision>
            <geometry>    
                <sphere radius = "${caster_wheel_radius}"/>
            </geometry>
            <origin xyz = "0 0 ${-wheel_radius + caster_wheel_radius}" rpy = "0 0 0"/>
        </collision>
        <xacro:sphere_inertia m = "0.01" r = "${caster_wheel_radius}"
                             o_xyz = "0 0 ${caster_wheel_radius}" o_rpy = "0 0 0"/>
    </link>


    <gazebo reference="caster_wheel_link">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>





 

    <joint name = "base_joint" type = "fixed">
        <parent link = "base_footprint"/>
        <child link = "base_link"/>
        <origin xyz = "0 0 ${wheel_radius}" rpy = "0 0 0"/>
    </joint>


    <joint name = "base_left_wheel_joint" type = "continuous">
        <parent link = "base_link"/>
        <child link = "left_wheel_link"/>
        <origin xyz = "${-length / 4} ${width / 2 + wheel_width / 2 + 0.01/4} 0" rpy = "0 0 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <joint name = "base_right_wheel_joint" type = "continuous">
        <parent link = "base_link"/>
        <child link = "right_wheel_link"/>
        <origin xyz = "${-length / 4} ${-width / 2 - wheel_width / 2 - 0.01/4} 0" rpy = "0 0 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <joint name = "base_caster_wheel_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "caster_wheel_link"/>
        <origin xyz = "${length / 4} 0 0" rpy = "0 0 0"/>
        <axis xyz = "0 0 1"/>
    </joint>

</robot>