<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name = "camera_box_length" value = "0.04"/>
    <xacro:property name = "camera_box_width" value = "0.06"/>
    <xacro:property name = "camera_box_height" value = "0.01"/>

    <link name = "camera_link">
        <visual>
             <geometry>
                <box size = "${camera_box_length} ${camera_box_width} ${camera_box_height}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 ${pi / 2} 0"/>
            <material name = "red"/>
        </visual>
        <collision>
             <geometry>
                <box size = "${camera_box_length} ${camera_box_width} ${camera_box_height}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
        </collision>
        <xacro:box_inertia m = "0.1" x = "${camera_box_length}" y = "${camera_box_width}" z = "${camera_box_height}"
                             o_xyz = "0 0 0" o_rpy = "0 0 0"/>
    </link>

    <link name = "camera_optical_frame"/>

     <joint name = "camera_optical_joint" type = "fixed">
        <parent link = "camera_link"/>
        <child link = "camera_optical_frame"/>
        <origin xyz = "0 0 0" rpy = "0 ${-pi / 2} 0"/>
        <axis xyz = "0 0 1"/>
    </joint>

    <joint name = "camera_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "camera_link"/>
        <origin xyz = "${length / 2} 0 ${height / 2}" rpy = "0 0 0"/>
        <axis xyz = "0 0 1"/>
    </joint>



    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        <sensor type="camera" name="camera">
            <pose>0 0 0 0 0 0</pose>
            <camera>
            <horizontal_fov>1.3963</horizontal_fov> 
            <image>
                <width>640</width>
                <height>480</height>
                <format>R8G8B8</format>
            </image>
            <clip>
                <near>0.002</near>
                <far>300</far>
            </clip>
            </camera>
            <plugin name="camera_plugin" filename="libgazebo_ros_camera.so">
            <topicName>camera_optical_frame</topicName>
            </plugin>
        </sensor>
    </gazebo>

</robot>