<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name = "lidar_radius" value = "0.05"/>
    <xacro:property name = "lidar_length" value = "0.03"/>

    <link name = "laser_frame">
        <visual>
            <geometry>
                <cylinder radius = "${lidar_radius}" length = "${lidar_length}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <material name = "red"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius = "${lidar_radius}" length = "${lidar_length}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
        </collision>
        <xacro:cylinder_inertia m = "0.1" r = "${lidar_radius}" h = "${lidar_length}"
                             o_xyz = "0 0 0" o_rpy = "0 0 0"/>
    </link>


    <joint name = "lidar_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "laser_frame"/>
        <origin xyz = "0 0 ${lidar_length/2 + height / 2 + wheel_radius}" rpy = "0 0 0"/>
        <axis xyz = "0 0 1"/>
    </joint>

    <gazebo reference="laser_frame">
        <material>Gazebo/Red</material>
        <sensor name="lidar_sensor" type="ray">
            <pose>0 0 0.1 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>20</update_rate>
            <ray>
            <scan>
                <horizontal>
                <samples>360</samples>
                <min_angle>-3.14</min_angle>
                <max_angle>3.14</max_angle>
                </horizontal>
            </scan>
            <range>
                <min>0.3</min>
                <max>10.0</max>
            </range>
            </ray>
            <plugin name="gazebo_ros_lidar_controller" filename="libgazebo_ros_ray_sensor.so">
            <ros>
                <namespace>/</namespace>
                <remapping>~/out:=scan</remapping>
            </ros>
            <output_type>sensor_msgs/LaserScan</output_type>
            <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>


</robot>