<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name = "camera_len" value = "0.01"/>
    <xacro:property name = "camera_width" value = "0.15"/>
    <xacro:property name = "camera_height" value = "0.08"/>


    <link name = "camera_lin">
        <visual>
            <geometry>
                <box size = "${camera_len} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <material name = "white"/>
        </visual>
        <collision>
            <geometry>
                <box size = "${camera_len} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
        </collision>
        <xacro:box_inertia m = "0.5" x = "${camera_len}" y = "${camera_width}" z = "${camera_height}"
                            o_xyz = "0 0 0" o_rpy = "0 0 0"/>
    </link>

    <joint name  = "camera_link_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "camera_lin"/>
        <origin xyz = "${base_len / 2} 0 ${base_height / 2}" rpy = "0 0 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <camera>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>15</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
                <optical_frame_id>camera_link_optical</optical_frame_id>
                <camera_info_topic>camera/camera_info</camera_info_topic>
            </camera>
            <always_on>1</always_on>
            <update_rate>20</update_rate>
            <visualize>true</visualize>
            <topic>camera/image_raw</topic>            
        </sensor>
    </gazebo>
</robot>