<?xml version = "1.0"?>
<robot xmlns:xacro = "http://www.ros.org/wiki/xacro">

    <xacro:property name = "base_len" value = "0.6"/>
    <xacro:property name = "base_width" value = "0.4"/>
    <xacro:property name = "base_height" value = "0.2"/>
    <xacro:property name = "radius" value = "0.1"/>
    <xacro:property name = "length" value = "0.05"/>
    <xacro:property name = "caster_radius" value = "0.05"/>
    <!-- write all things inside the robot tag -->


    <link name = "base_footprint"/>


    <link name = "base_link">
        <visual>
            <geometry>
                <box size = "${base_len} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz = "0 0 ${radius}" rpy = "0 0 0"/>
            <material name = "green"/>
        </visual>
        <collision>
            <geometry>
                <box size = "${base_len} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz = "0 0 ${radius}" rpy = "0 0 0"/>
        </collision>
        <xacro:box_inertia m = "5.0" x = "${base_len}" y = "${base_width}" z = "${base_height}"
                           o_xyz = "0 0 ${radius}" o_rpy = "0 0 0"/>
    </link>

    <link name ="lider_link">
        <visual>
            <geometry>
                <cylinder radius = "${radius}" length = "${length}"/>
            </geometry>
            <origin xyz = "0 0 0" rpy = "0 0 0"/>
            <material name = "white"/>
        </visual>
    </link>


    <xacro:macro name = "wheel_link" params="prefix">
        <link name ="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius = "${radius}" length = "${length}"/>
                </geometry>
                <origin xyz = "0 0 0" rpy = "${pi / 2.0} 0 0"/>
                <material name = "red"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius = "${radius}"/>
                </geometry>
                <origin xyz = "0 0 0" rpy = "0 0 0"/>
            </collision>
            <xacro:wheel m = "1.0" r = "${radius}" h = "${length}" o_xyz = "0 0 0" o_rpy = "${pi / 2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="left"/>
    <xacro:wheel_link prefix="right"/>


    <link name = "caster_wheel">
        <visual>
            <geometry>
                <sphere radius = "${caster_radius}"/>
            </geometry>
            <origin xyz = "0 0 ${-radius + caster_radius}" rpy = "0 0 0"/>
            <material name = "red"/>
        </visual>
         <collision>
                <geometry>
                    <sphere radius = "${caster_radius}"/>
                </geometry>
                <origin xyz = "0 0 ${-radius + caster_radius}" rpy = "0 0 0"/>
         </collision>
        <xacro:caster_wheel m = "0.5" r = "${caster_radius}"
                             o_xyz = "0 0 ${-radius + caster_radius}" o_rpy = "0 0 0"/>
    </link>




    

    <joint name = "base_joint" type = "fixed">
        <parent link = "base_footprint"/>
        <child link = "base_link"/>
        <origin xyz = "0 0 ${radius}" rpy = "0 0 0"/>
    </joint>

    <joint name = "base_lider_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "lider_link"/>
        <origin xyz = "0 0 ${base_height + length / 2.0}" rpy = "0 0 0"/>
    </joint>

    <joint name = "base_wheel_joint_1" type = "continuous">
        <parent link = "base_link"/>
        <child link = "left_wheel_link"/>
        <origin xyz = "${- base_len / 4 } ${ base_width / 2 + length / 2 } 0" rpy = "0 0 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <joint name = "base_wheel_joint_2" type = "continuous">
        <parent link = "base_link"/>
        <child link = "right_wheel_link"/>
        <origin xyz = "${- base_len / 4} ${-base_width / 2 - length / 2} 0" rpy = "0 0 0"/>
        <axis xyz = "0 1 0"/>
    </joint>

    <joint name = "base_caster_joint" type = "fixed">
        <parent link = "base_link"/>
        <child link = "caster_wheel"/>
        <origin xyz = "${base_len / 2 - base_len / 8} 0 0" rpy = "0 0 0"/>
        <axis xyz = "0 0 1"/>
    </joint>


</robot>